apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: clickhouse
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/albertopeisan/tb-argocd'
    - 'https://altinity.github.io/kubernetes-blueprints-for-clickhouse'
  destinations:
    - namespace: 'clickhouse'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
