apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/albertopeisan/tb-argocd
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: prometheus
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
