apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  sources:
    - chart: argo-cd
      helm:
        valueFiles:
          - $values/charts/argocd/values.yaml
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.8.23
    - ref: values
      repoURL: https://github.com/albertopeisan/tb-argocd.git
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
