apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: https://github.com/albertopeisan/tb-argocd
    path: projects
    directory:
      recurse: true
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
