apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  destination:
    namespace: clickhouse
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - jsonPointers:
        - /data/admin-password
      kind: Secret
      name: clickhouse
      namespace: clickhouse
  project: clickhouse
  sources:
    - chart: clickhouse
      helm:
        valueFiles:
          - $values/charts/clickhouse/values.yaml
          - $values/charts/clickhouse-zookeeper/values.yaml
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 8.0.0
    - ref: values
      repoURL: https://github.com/albertopeisan/tb-argocd.git
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
