apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse
  namespace: argocd
spec:
  project: clickhouse
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: clickhouse
      targetRevision: 8.0.0
      helm:
        valueFiles:
          - $values/charts/clickhouse/values.yaml
    - repoURL: https://github.com/albertopeisan/tb-argocd.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: clickhouse
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: clickhouse
      namespace: clickhouse
      jsonPointers:
        - /data/admin-password
