apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: grafana
  sources:
    - chart: grafana
      helm:
        valueFiles:
          - $values/charts/grafana/values.yaml
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: grafana-8.11.2
    - ref: values
      repoURL: https://github.com/albertopeisan/tb-argocd.git
      targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
